### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gobengo** [fanout/apollo-demo#3]
@jkarneges How do you want to license this?

I haven't seen any other public code out there using Apollo + Pulumi. The official apollo docs only say how to use the serverless framework. https://www.apollographql.com/docs/apollo-server/deployment/lambda#deploying-with-the-serverless-framework

If license allows, I kinda wanna publish a repo from approximately this commit (or after milestone 2) that is just a minimal example of Pulumi + Lambda + Apollo, before we add pushpin stuff.

Good to have a license no matter what.

**Comment by jkarneges** [comment]
Let's do MIT
